version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.1.2

jobs:
  pip-install:
    docker:
      - image: cimg/python:3.9.16
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: pip-{{ checksum "pyproject.toml" }}-v1
      - run:
          name: Install pip dependencies
          command: |
            if [[ -d ".venv" ]]; then
              echo "Virtual environment restored from cache, skipping pip install"
            else
              python3 -m venv .venv
              source .venv/bin/activate
              pip install -e .[dev-pinned,pinned]
            fi
      - save_cache:
          key: pip-{{ checksum "pyproject.toml" }}-v1
          paths:
            - .venv
            - integreat_compass.egg-info
            - /home/circleci/.cache/pip
      - persist_to_workspace:
          root: .
          paths:
            - .venv
            - integreat_compass.egg-info
  npm-install:
    docker:
      - image: "cimg/node:lts"
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}-v1
      - run:
          name: Install npm dependencies
          command: |
            if [[ -d "node_modules" ]]; then
              echo "Node modules restored from cache, skipping npm install"
            else
              npm ci
            fi
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}-v1
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  black:
    docker:
      - image: cimg/python:3.9.16
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Enable virtual environment
          command: echo "source .venv/bin/activate" >> $BASH_ENV
      - run:
          name: Check black code style
          command: black --check .
  compile-translations:
    docker:
      - image: cimg/python:3.9.16
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install gettext
          command: sudo apt-get update && sudo apt-get install gettext
      - run:
          name: Enable virtual environment
          command: echo "source .venv/bin/activate" >> $BASH_ENV
      - run:
          name: Compile translation file
          command: |
            cd integreat_compass
            integreat-compass-cli compilemessages --settings=integreat_compass.core.circleci_settings
      - persist_to_workspace:
          root: .
          paths:
            - integreat_compass/locale/*/LC_MESSAGES/django.mo
  djlint:
    docker:
      - image: cimg/python:3.9.16
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Enable virtual environment
          command: echo "source .venv/bin/activate" >> $BASH_ENV
      - run:
          name: Check formatting of Django templates
          command: djlint --check --lint integreat_compass
  eslint:
    docker:
      - image: "cimg/node:lts"
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint static CSS, JS & YAML files
          command: npx eslint . --no-error-on-unmatched-pattern
  isort:
    docker:
      - image: cimg/python:3.9.16
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Enable virtual environment
          command: echo "source .venv/bin/activate" >> $BASH_ENV
      - run:
          name: Check isort code style
          command: isort --check .
  prettier:
    docker:
      - image: "cimg/node:lts"
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check formatting of CSS & JS files
          command: npx prettier --check .
  pylint:
    docker:
      - image: "cimg/python:3.9.16"
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run pylint
          command: ./tools/pylint.sh
  webpack:
    docker:
      - image: "cimg/node:lts"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Compile and bundle CSS and JS
          command: npm run prod
      - persist_to_workspace:
          root: .
          paths:
            - integreat_compass/static/dist
            - integreat_compass/webpack-stats.json
  build-package:
    docker:
      - image: cimg/python:3.9.16
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Enable virtual environment
          command: echo "source .venv/bin/activate" >> $BASH_ENV
      - run:
          name: Build integreat-compass package
          command: python3 -m build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  bump-dev-version:
    docker:
      - image: cimg/python:3.9.16
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Enable virtual environment
          command: echo "source .venv/bin/activate" >> $BASH_ENV
      - run:
          name: Bump version
          command: |
            # Install recent version of pip
            echo "Upgrade pip to make sure 'pip index' is available"
            pip install --upgrade pip
            # Check which versions of integreat-compass are available on the TestPyPI repository
            AVAILABLE_VERSIONS=$(pip index versions integreat-compass --pre -i https://test.pypi.org/simple/)
            echo "Current available versions on TestPyPI: ${AVAILABLE_VERSIONS}"
            CURRENT_ALPHA_VERSION=$(echo "${AVAILABLE_VERSIONS}" | head -n 1)
            echo "Most recent version on TestPyPI: ${CURRENT_ALPHA_VERSION}"
            CURRENT_ALPHA_VERSION=$(echo "${CURRENT_ALPHA_VERSION}" | sed "s/integreat-compass (\([^()]*\)a0)/\1-alpha/")
            echo "Version converted to alternative format: ${CURRENT_ALPHA_VERSION}"
            # Get current prod version
            CURRENT_VERSION=$(python -c "import integreat_compass; print(integreat_compass.__version__)")
            echo "Current production version: ${CURRENT_VERSION}"
            # Bump version to current alpha version if it is newer
            # Attention: exit(True) in Python means exit(1) which is False in Bash :)
            if python -c "from looseversion import LooseVersion; exit(LooseVersion('${CURRENT_VERSION}') > LooseVersion('${CURRENT_ALPHA_VERSION}'))"; then
              echo "Bump to the currently existing version"
              bumpver update -n --set-version="${CURRENT_ALPHA_VERSION}" --no-commit
            fi
            # Bump version to next alpha version
            echo "Bump to the next version"
            bumpver update -n -t alpha --no-commit
      - persist_to_workspace:
          root: .
          paths:
            - pyproject.toml
            - integreat_compass/__init__.py
  publish-package:
    docker:
      - image: cimg/python:3.9.16
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Enable virtual environment
          command: echo "source .venv/bin/activate" >> $BASH_ENV
      - run:
          name: Publish integreat-compass package to (Test-)PyPI
          command: twine upload --non-interactive ./dist/integreat-compass-*.tar.gz

workflows:
  develop:
    jobs:
      - pip-install:
          filters:
            branches:
              ignore: main
      - npm-install:
          filters:
            branches:
              ignore: main
      - webpack:
          requires:
            - npm-install
      - compile-translations:
          requires:
            - pip-install
      - black:
          requires:
            - pip-install
      - djlint:
          requires:
            - pip-install
      - eslint:
          requires:
            - npm-install
      - isort:
          requires:
            - pip-install
      - prettier:
          requires:
            - npm-install
      - pylint:
          requires:
            - pip-install
      - shellcheck/check:
          dir: ./tools
          external_sources: true
          filters:
            branches:
              ignore: main
      - bump-dev-version:
          filters:
            branches:
              only:
                - develop
                - /.*-publish-dev-package/
          requires:
            - pip-install
      - build-package:
          name: build-dev-package
          requires:
            - webpack
            - compile-translations
            - bump-dev-version
      - publish-package:
          name: publish-dev-package
          context: pypi-test
          filters:
            branches:
              only:
                - develop
                - /.*-publish-dev-package/
          requires:
            - build-dev-package

  main:
    jobs:
      - pip-install:
          name: pip-install-main
          filters:
            branches:
              only: main
  deploy:
    jobs:
      - pip-install:
          name: pip-install-deploy
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
